### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [molpopgen/libsequence#37]
I would like to point out that identifiers like “[`__POLY_TABLE_TCC__`](https://github.com/molpopgen/libsequence/blob/1cfdcabf8c851d4e86cd58d3d4c3055fa52fcc0e/Sequence/bits/PolyTable.tcc#L27 "Update candidate")” and “[`__SEQ_SAMFUNCTIONS_HPP__`](https://github.com/molpopgen/libsequence/blob/1cfdcabf8c851d4e86cd58d3d4c3055fa52fcc0e/Sequence/samfunctions.hpp#L1 "Another update candidate")” [do eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by molpopgen** [comment]
Closing b/c this is very low priority.  The chances of a name clash are vanishingly small and there are other things to do with this project in the short term.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?

**Comment by molpopgen** [comment]
Are you a bot?  You have opened this issue on a LOT of project recently, and seem to auto-reply with the same text.
